
package com.honpe.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PuPriceQuerySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PuPriceQuerySoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param suppliername
     * @param querycondition
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOEMProductsTotal", action = "http://tempuri.org/GetOEMProductsTotal")
    @WebResult(name = "GetOEMProductsTotalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOEMProductsTotal", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProductsTotal")
    @ResponseWrapper(localName = "GetOEMProductsTotalResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProductsTotalResponse")
    public String getOEMProductsTotal(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "querycondition", targetNamespace = "http://tempuri.org/")
        String querycondition,
        @WebParam(name = "suppliername", targetNamespace = "http://tempuri.org/")
        String suppliername);

    /**
     * 
     * @param pagesize
     * @param suppliername
     * @param querycondition
     * @param md5
     * @param userid
     * @param currentpage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOEMProducts", action = "http://tempuri.org/GetOEMProducts")
    @WebResult(name = "GetOEMProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOEMProducts", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProducts")
    @ResponseWrapper(localName = "GetOEMProductsResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProductsResponse")
    public String getOEMProducts(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "querycondition", targetNamespace = "http://tempuri.org/")
        String querycondition,
        @WebParam(name = "pagesize", targetNamespace = "http://tempuri.org/")
        int pagesize,
        @WebParam(name = "currentpage", targetNamespace = "http://tempuri.org/")
        int currentpage,
        @WebParam(name = "suppliername", targetNamespace = "http://tempuri.org/")
        String suppliername);

    /**
     * 
     * @param requestNo
     * @param querycondition
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOEMProductsDetail", action = "http://tempuri.org/GetOEMProductsDetail")
    @WebResult(name = "GetOEMProductsDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOEMProductsDetail", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProductsDetail")
    @ResponseWrapper(localName = "GetOEMProductsDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMProductsDetailResponse")
    public String getOEMProductsDetail(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "requestNo", targetNamespace = "http://tempuri.org/")
        String requestNo,
        @WebParam(name = "querycondition", targetNamespace = "http://tempuri.org/")
        String querycondition);

    /**
     * 
     * @param requestNo
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOEMAttachs", action = "http://tempuri.org/GetOEMAttachs")
    @WebResult(name = "GetOEMAttachsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOEMAttachs", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMAttachs")
    @ResponseWrapper(localName = "GetOEMAttachsResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetOEMAttachsResponse")
    public String getOEMAttachs(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "requestNo", targetNamespace = "http://tempuri.org/")
        String requestNo);

    /**
     * 
     * @param querycondition
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPuPriceItemTotal", action = "http://tempuri.org/GetPuPriceItemTotal")
    @WebResult(name = "GetPuPriceItemTotalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPuPriceItemTotal", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemTotal")
    @ResponseWrapper(localName = "GetPuPriceItemTotalResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemTotalResponse")
    public String getPuPriceItemTotal(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "querycondition", targetNamespace = "http://tempuri.org/")
        String querycondition);

    /**
     * 
     * @param pagesize
     * @param querycondition
     * @param md5
     * @param userid
     * @param currentpage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPuPriceItem", action = "http://tempuri.org/GetPuPriceItem")
    @WebResult(name = "GetPuPriceItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPuPriceItem", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItem")
    @ResponseWrapper(localName = "GetPuPriceItemResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemResponse")
    public String getPuPriceItem(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "querycondition", targetNamespace = "http://tempuri.org/")
        String querycondition,
        @WebParam(name = "pagesize", targetNamespace = "http://tempuri.org/")
        int pagesize,
        @WebParam(name = "currentpage", targetNamespace = "http://tempuri.org/")
        int currentpage);

    /**
     * 
     * @param billID
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPuPriceItemDetails", action = "http://tempuri.org/GetPuPriceItemDetails")
    @WebResult(name = "GetPuPriceItemDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPuPriceItemDetails", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemDetails")
    @ResponseWrapper(localName = "GetPuPriceItemDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemDetailsResponse")
    public String getPuPriceItemDetails(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "billID", targetNamespace = "http://tempuri.org/")
        String billID);

    /**
     * 
     * @param requestNo
     * @param suppliername
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPuPriceItemRecord", action = "http://tempuri.org/GetPuPriceItemRecord")
    @WebResult(name = "GetPuPriceItemRecordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPuPriceItemRecord", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemRecord")
    @ResponseWrapper(localName = "GetPuPriceItemRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuPriceItemRecordResponse")
    public String getPuPriceItemRecord(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "requestNo", targetNamespace = "http://tempuri.org/")
        String requestNo,
        @WebParam(name = "suppliername", targetNamespace = "http://tempuri.org/")
        String suppliername);

    /**
     * 
     * @param queryInfo
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddPuPriceItems", action = "http://tempuri.org/AddPuPriceItems")
    @WebResult(name = "AddPuPriceItemsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddPuPriceItems", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.AddPuPriceItems")
    @ResponseWrapper(localName = "AddPuPriceItemsResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.AddPuPriceItemsResponse")
    public String addPuPriceItems(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "queryInfo", targetNamespace = "http://tempuri.org/")
        String queryInfo);

    /**
     * 
     * @param queryInfo
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EditPuPriceItems", action = "http://tempuri.org/EditPuPriceItems")
    @WebResult(name = "EditPuPriceItemsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EditPuPriceItems", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.EditPuPriceItems")
    @ResponseWrapper(localName = "EditPuPriceItemsResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.EditPuPriceItemsResponse")
    public String editPuPriceItems(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "queryInfo", targetNamespace = "http://tempuri.org/")
        String queryInfo);

    /**
     * 
     * @param queryInfo
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddPuSuppliersItem", action = "http://tempuri.org/AddPuSuppliersItem")
    @WebResult(name = "AddPuSuppliersItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddPuSuppliersItem", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.AddPuSuppliersItem")
    @ResponseWrapper(localName = "AddPuSuppliersItemResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.AddPuSuppliersItemResponse")
    public String addPuSuppliersItem(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "queryInfo", targetNamespace = "http://tempuri.org/")
        String queryInfo);

    /**
     * 
     * @param queryInfo
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EditPuSuppliersItem", action = "http://tempuri.org/EditPuSuppliersItem")
    @WebResult(name = "EditPuSuppliersItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EditPuSuppliersItem", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.EditPuSuppliersItem")
    @ResponseWrapper(localName = "EditPuSuppliersItemResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.EditPuSuppliersItemResponse")
    public String editPuSuppliersItem(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "queryInfo", targetNamespace = "http://tempuri.org/")
        String queryInfo);

    /**
     * 
     * @param sid
     * @param md5
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPuSuppliersItem", action = "http://tempuri.org/GetPuSuppliersItem")
    @WebResult(name = "GetPuSuppliersItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPuSuppliersItem", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuSuppliersItem")
    @ResponseWrapper(localName = "GetPuSuppliersItemResponse", targetNamespace = "http://tempuri.org/", className = "com.honpe.erp.GetPuSuppliersItemResponse")
    public String getPuSuppliersItem(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        String md5,
        @WebParam(name = "sid", targetNamespace = "http://tempuri.org/")
        String sid);

}
